services:
  - type: web
    name: premier-league-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run Home.py --server.port 10000 --server.enableCORS false
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10